/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: { sans: ["Inter", "sans-serif"] },
      colors: {
        primary:   "#091426",
        "primary-container": "#1e293b",
        "on-primary-container": "#8590a6",
        secondary: "#505f76",
        "secondary-container": "#d0e1fb",
        tertiary:  "#eb6905",
        surface:   "#f7f9fb",
        "surface-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-high": "#e6e8ea",
        "surface-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#45474c",
        outline:   "#75777d",
        "outline-variant": "#c5c6cd",
        error:     "#ba1a1a",
        "error-container": "#ffdad6",
        accent:    "#eb6905",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-main": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-data": ["14px", { lineHeight: "1.5", letterSpacing: "-0.01em" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
