"""Add user_override to DXFBlock

Revision ID: 290b7209b478
Revises: a17ee6ae145e
Create Date: 2026-06-07 16:22:13.249106

"""
from alembic import op
import sqlalchemy as sa


revision = '290b7209b478'
down_revision = 'a17ee6ae145e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dxf_blocks', sa.Column('user_override', sa.String(length=100), nullable=True))
    op.add_column('quantity_suggestions', sa.Column('user_override', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quantity_suggestions', 'user_override')
    op.drop_column('dxf_blocks', 'user_override')
    # ### end Alembic commands ###
