"""Add Phase 3 models for CAD automation

Revision ID: a17ee6ae145e
Revises: 0003
Create Date: 2026-06-07 16:09:12.762081

"""
from alembic import op
import sqlalchemy as sa
import app.db.models
from sqlalchemy.dialects import postgresql

revision = 'a17ee6ae145e'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layer_mapping_templates',
    sa.Column('id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.models.GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mappings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_mappings_v2',
    sa.Column('id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('project_id', app.db.models.GUID(length=36), nullable=True),
    sa.Column('block_name', sa.String(length=255), nullable=False),
    sa.Column('discipline', sa.String(length=10), nullable=False),
    sa.Column('task_key', sa.String(length=100), nullable=False),
    sa.Column('mapped_by', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_community', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer_mappings_v2',
    sa.Column('id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('project_id', app.db.models.GUID(length=36), nullable=True),
    sa.Column('layer_name', sa.String(length=255), nullable=False),
    sa.Column('discipline', sa.String(length=10), nullable=False),
    sa.Column('task_key', sa.String(length=100), nullable=False),
    sa.Column('mapped_by', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_community', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawing_revisions',
    sa.Column('id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('drawing_id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diff_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dxf_analysis_jobs',
    sa.Column('id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('drawing_id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('entities_found', sa.Integer(), nullable=False),
    sa.Column('layers_found', sa.Integer(), nullable=False),
    sa.Column('suggestions_generated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dxf_blocks',
    sa.Column('id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('drawing_id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('block_name', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('classified_as', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dxf_entities',
    sa.Column('id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('drawing_id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('layer_name', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('geometry_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('block_name', sa.String(length=255), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('handle', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dxf_layers',
    sa.Column('id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('drawing_id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('layer_name', sa.String(length=255), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('classified_as', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('strategy_used', sa.String(length=50), nullable=True),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.Column('user_override', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantity_suggestions',
    sa.Column('id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('project_id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('drawing_id', app.db.models.GUID(length=36), nullable=False),
    sa.Column('discipline', sa.String(length=10), nullable=False),
    sa.Column('task_key', sa.String(length=100), nullable=False),
    sa.Column('task_label', sa.String(length=255), nullable=True),
    sa.Column('source_layer', sa.String(length=255), nullable=True),
    sa.Column('source_block', sa.String(length=255), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('entity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('final_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('formula_applied', sa.Text(), nullable=True),
    sa.Column('suggested_rate_id', app.db.models.GUID(length=36), nullable=True),
    sa.Column('suggested_rate_confidence', sa.Float(), nullable=True),
    sa.Column('classification_method', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', app.db.models.GUID(length=36), nullable=True),
    sa.Column('final_quantity', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_rate_id'], ['rate_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('projects', 'grist_doc_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('grist_doc_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('quantity_suggestions')
    op.drop_table('dxf_layers')
    op.drop_table('dxf_entities')
    op.drop_table('dxf_blocks')
    op.drop_table('dxf_analysis_jobs')
    op.drop_table('drawing_revisions')
    op.drop_table('layer_mappings_v2')
    op.drop_table('block_mappings_v2')
    op.drop_table('layer_mapping_templates')
    # ### end Alembic commands ###
